<?php

namespace App\Http\Controllers\Jewelry;

use App\Http\Controllers\BaseController;
use App\Models\AmlFlaggedTransaction;
use Illuminate\Http\Request;

/**
 * Read + review-action only — rows here are system-generated by
 * AmlComplianceService, never created directly by a user.
 */
class AmlFlaggedTransactionController extends BaseController
{
    public function index(Request $request)
    {
        $this->authorizeForUser(request()->user('api'), 'view', AmlFlaggedTransaction::class);
        $perPage = (int) $request->input('limit', 15);
        $query = AmlFlaggedTransaction::query()->with(['sale', 'client']);

        if ($request->filled('review_status')) {
            $query->where('review_status', $request->input('review_status'));
        }

        $total = $query->count();
        if ($perPage === -1) {
            $perPage = max($total, 1);
        }
        $page = (int) $request->input('page', 1);
        $items = $query->orderByDesc('id')
            ->offset(max($page - 1, 0) * $perPage)
            ->limit($perPage)
            ->get();

        return response()->json(['data' => $items, 'totalRows' => $total]);
    }

    public function show($id)
    {
        $this->authorizeForUser(request()->user('api'), 'view', AmlFlaggedTransaction::class);
        $item = AmlFlaggedTransaction::with(['sale', 'client'])->findOrFail($id);

        return $this->sendResponse($item, 'Flagged transaction retrieved successfully.');
    }

    /**
     * Mark a flagged transaction as cleared or escalate it as reported.
     */
    public function update(Request $request, $id)
    {
        $this->authorizeForUser(request()->user('api'), 'update', AmlFlaggedTransaction::class);
        $request->validate([
            'review_status' => 'required|in:pending,cleared,reported',
            'notes' => 'nullable|string',
        ]);

        $item = AmlFlaggedTransaction::findOrFail($id);
        $item->update([
            'review_status' => $request->input('review_status'),
            'notes' => $request->input('notes', $item->notes),
            'reviewed_by' => optional(request()->user('api'))->id,
            'reviewed_at' => now(),
        ]);

        return $this->sendResponse($item, 'Flagged transaction updated successfully.');
    }
}
