<?php

namespace App\Http\Controllers\Jewelry;

use App\Http\Controllers\BaseController;
use App\Models\ConsignmentSettlement;
use App\Services\ConsignmentSettlementService;
use Illuminate\Http\Request;

/**
 * Read + settle-action only — rows here are system-generated by
 * ConsignmentSettlementService when a consigned item sells, never created
 * directly by a user.
 */
class ConsignmentSettlementController extends BaseController
{
    public function __construct(protected ConsignmentSettlementService $service)
    {
    }

    public function index(Request $request)
    {
        $this->authorizeForUser(request()->user('api'), 'view', ConsignmentSettlement::class);
        $perPage = (int) $request->input('limit', 15);
        $query = ConsignmentSettlement::query()->with(['product', 'sale']);

        if ($request->filled('status')) {
            $query->where('status', $request->input('status'));
        }

        $total = $query->count();
        if ($perPage === -1) {
            $perPage = max($total, 1);
        }
        $page = (int) $request->input('page', 1);
        $items = $query->orderByDesc('id')
            ->offset(max($page - 1, 0) * $perPage)
            ->limit($perPage)
            ->get();

        return response()->json(['data' => $items, 'totalRows' => $total]);
    }

    public function show($id)
    {
        $this->authorizeForUser(request()->user('api'), 'view', ConsignmentSettlement::class);
        $item = ConsignmentSettlement::with(['product', 'sale'])->findOrFail($id);

        return $this->sendResponse($item, 'Consignment settlement retrieved successfully.');
    }

    public function settle(Request $request, $id)
    {
        $this->authorizeForUser(request()->user('api'), 'update', ConsignmentSettlement::class);
        $item = ConsignmentSettlement::findOrFail($id);

        if ($item->status !== 'pending') {
            return $this->sendError('Only a pending settlement can be marked settled.');
        }

        $item = $this->service->markSettled($item, optional(request()->user('api'))->id);

        return $this->sendResponse($item, 'Settlement marked as settled.');
    }
}
